config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Fashionfly::Application.routes.draw do
  get 'app-entwickler-finden', to: 'redirector#appentwickler', as: 'app'
  get 'programmierer-hamburg', to: 'redirector#programmierer', as: 'prog'
  get 'internet-agentur-hamburg', to: 'redirector#internetagentur', as: 'int'

  get 'brandet_categories/show'

  get 'blogs/edit'

  get 'blogs/show'

  admin_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:is_admin?) && current_user.is_admin?
  end

  team_constraint  = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:is_team?) && current_user.is_team?
  end

  post '/rate' => 'rater#create', :as => 'rate'
  constraints team_constraint do
    mount Lit::Engine => '/lit'
  end

  namespace :backend do
    constraints admin_constraint do
      mount Sidekiq::Web => '/sidekiq'
    end
    root to: 'dashboards#show'
    resources :configurations
    resources :scopes do
      resources :outfit_categories
      resources :categories
      resources :contests
      resources :pages
      resources :affiliates do
        resources :mappings
      end
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    confirmations: 'users/confirmations',
                                    registrations: 'users/registrations' }

  resources :widgets

  namespace :endpoint do
    namespace :v1 do
      scope defaults: { format: 'json' } do
        resources :scopes, only: %i[index show] do
          resources :categories, only: %i[index show]
          resources :products, only: %i[index show]
          resources :collections_categories, only: %i[index show]
          resources :collections, except: :destroy do
            resources :comments
          end
          resources :users
          resources :session
        end
      end
    end
  end

  scope '/:locale' do
    get 'hashtags/:hashtag',   to: 'hashtags#show',      as: :hashtag
    get 'hashtags',            to: 'hashtags#index',     as: :hashtags
    resources :shops
    resources :banners
    resources :entries
    resources :brands, only: %i[show index]
    get 'property_shop_link', to: 'properties#property_shop_link', as: :property_shop_link
    get 'property_collection_link', to: 'properties#property_collection_link', as: :property_collection_link
    get 'property_category_link', to: 'properties#property_category_link', as: :property_category_link

    resource :property, only: %i[edit update]
    get 'shoplist', to: 'shops#list', as: :shoplist
    get 'shopref/:id', to: 'shops#ref', as: :shopref
    get 'language', to: 'welcome#language'
    resources :contests
    resources :styles, only: %i[show index]
    resources :profiles, only: %i[show update edit] do
      get 'outfits', to: 'profiles#outfits'
      get 'favorites', to: 'profiles#favorites'
      resource :blog
    end
    get '/product_clicked/:id', to: 'products#clicked', as: :prodclick
    patch 'email_edit', to: 'profiles#email_edit', as: :email_edit
    get 'prodref/:id', to: 'products#ref', as: :productref
    resources :products, only: %i[show index] do
      resources :favorites, only: %i[create destroy]
    end
    resources :collections, only: %i[show index] do
      resources :favorites, only: %i[create destroy]
      resources :comments, only: %i[create destroy update]
    end
    post 'product_partner', to: 'products#refshop', as: :refshop
    resources :categories
    resources :outfit_categories
    mount FashionFlyEditor::Engine => '/combine'
    namespace :api do
      match 'categories', to: 'categories#index', via: [:options]
      resources :categories
      resources :colors
      resources :products
    end
    get 'login', to: 'users#new', as: 'login'
    get 'faq', to: 'static#faq', as: 'faq'
    get 'about', to: 'static#about', as: 'about'
    get 'team', to: 'static#team', as: 'team'
    get 'disclaimer', to: 'static#disclaimer', as: 'disclaimer'
    get 'terms', to: 'static#terms', as: 'terms'
    get 'impress', to: 'static#impress', as: 'impress'
    get 'privacy', to: 'static#privacy', as: 'privacy'
    get 'sitemap.xml', to: 'welcome#sitemap', format: :xml, as: 'sitemap', defaults: { format: 'xml' }
    get 'robots.txt', to: 'welcome#robot', format: :text, as: 'robot', defaults: { format: 'text' }
    root 'welcome#index'
    get ':brand/:category', to: 'brandet_categories#show', as: 'brand_category'
  end

  # Parameter constraint checks if path does not begin with locale and only in that case redirects to localized version. This way we will avoid infinite redirects for non-existing urls.
  get '/*path', to: 'language#select', constraints: { path: %r{(?!(#{I18n.available_locales.join("|")})/).*} },
                format: false
end

app/controllers/collections_controller.rb
# frozen_string_literal: true

class CollectionsController < ScopeController
  before_action :check_collection, only: :show

  def index
    @outfit_category = true
    @collections = CollectionSearchService.new(@scope, params).collections
  end

  def show
    # Hack for some reason i got an alert user allready signed in notice
    # I think it is a timing issue. Check Collection is called before the call back
    # assign_collection saved the collection to the user
    flash.delete(:alert)
    visit_me @collection
  end

  def check_collection
    @collection = FashionFlyEditor::Collection.find(params[:id])
    if @collection.blank?
      flash[:alert] = I18n.t('action.collection_not_found')
      redirect_to collections_path(@scope.locale)
    end
    return unless @collection.present? && @collection.published == false

    if cookies[:collection].present? && cookies[:collection].to_i == @collection.id
      flash[:alert] = I18n.t('action.required_to_signed_in')
      redirect_to new_user_session_path(locale: assigned_locale)
    else
      flash[:alert] = I18n.t('action.collection_not_found')
      redirect_to collections_path(@scope.locale)
    end
  end
end

app/controllers/endpoint/v1/collections_controller.rb
# frozen_string_literal: true

module Endpoint
  module V1
    class CollectionsController < Endpoint::V1::ScopesController
      before_action :find_scope
      before_action :find_collection, only: :show

      def index
        @collections = CollectionSearchService.new(@scope, params).collections
      end

      def show
        @with_extra_info = true
      end

      protected

      def find_collection
        collection_id = params[:collection_id] || params[:id]
        @collection = @scope.collections.find(collection_id)
      end
    end
  end
end

app/helpers/collections_helper.rb
# frozen_string_literal: true

module CollectionsHelper
  def breadcrumb_collection_text(collection)
    category = collection.category
    collection_category_breadcrumb_text category
  end

  def collection_category_breadcrumb_text(category)
    return '' if category.blank?

    prefix = if category.parent_type == 'Scope'
               nil
             else
               collection_category_breadcrumb_text category.parent
             end
    (prefix.present? ? "#{prefix}/" : '') + category.name
  end

  def render_embed_code(collection)
    content =  javascript_include_tag javascript_url('widget'), type: 'text/javascript'
    content << content_tag(:div, 'data' => collection.id, 'host' => request.host_with_port,
                                 'class' => 'fashionfly-widget') do
      link_to @collection.title, collection_url(assigned_locale, @collection), title: @collection.title,
                                                                               alt: @collection.title
    end
  end

  def linked_description(collection)
    content = collection.description
    collection.hashtags.each do |hashtag|
      content.gsub!("##{hashtag.name}",
                    link_to("##{hashtag.name}", hashtag_path(locale: assigned_locale, hashtag: hashtag.name)).to_s)
    end
    simple_format content
  end

  def information_span(item, collection)
    product = collection_products(collection)[item]
    return if product.blank?

    content_tag(:span, class: 'information_span', id: "#{item}infobox") do
      inner = content_tag(:span, class: 'information_left') do
        right = content_tag(:span, product.try(:brand).try(:name))
        right << content_tag(:span, '/')
        right << content_tag(:span, product.categories.last.name)
      end
      inner << content_tag(:span, class: 'information_right') do
        number_to_currency(product.price, unit: product.currencyCode)
      end
      content_tag(:span, class: :inner) do
        inner
      end
    end
  end

  def collection_products(collection)
    return @collection_products if @collection_products.present?

    @collection_products = {}
    collection.products.each do |product|
      @collection_products[product.id] = product
    end
    @collection_products
  end

  def css_calculate_dimension(item, _collection)
    left    = 566.0 * (item.position_x.to_f / @collection.width)
    top     = 442.0 * (item.position_y.to_f / @collection.height)
    width   = 566.0 * (item.width.to_f / @collection.width)
    height  = 442.0 * (item.height.to_f / @collection.height)
    "left:#{left}px;top:#{top}px;height:#{height}px;width:#{width}px;transform: rotate(#{item.rotation}deg)"
  end
end

app/views/collections/_collections.html.erb
<%= render 'collections/filter' %>
<% if @category.present? %>
  <% content_for :title do "#{@category.name} | #{Settings.app.name}"; end %>
  <h1 style="text-align:left; padding-top:0px;padding-bottom:20px"><%= @category.name %></h1>

  <% content_for :meta do %>

  <meta property="og:title" content="<%= @category.name %> | <%= Settings.app.name %>"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="<%=category_url(assigned_locale, @category.slug)%>"/>
  <meta property="og:locale" content="<%=assigned_locale%>" />
  <% if @scope.page("__categories__#{@category.try(:slug)}").present? %>
    <meta property="og:description" content="<%= strip_tags(@scope.page("__categories__#{@category.try(:slug)}").body).squish %>" />
  <% end %>
  <!--
  <PageMap>
     <DataObject type="document">
        <Attribute name="title"><%= @category.name %> | <%= Settings.app.name %></Attribute>
        <Attribute name="author">FashionFly</Attribute>
        <% if @scope.page("__categories__#{@category.try(:slug)}").present? %>
          <Attribute name="description">
            <%= strip_tags(@scope.page("__categories__#{@category.try(:slug)}").body).squish %>
          </Attribute>
        <% end %>
        <Attribute name="category"><%= @category.name %></Attribute>
        <Attribute name="last_update"><%= @category.updated_at %></Attribute>
     </DataObject>
  </PageMap>
  -->
  <% end %>
<% end %>

<div class="white_box pagination_options" ng-controller="FilterController">
  <%= t('.sort_by') %>
  <select id="sort_by"  ng-change="changeSelect('sort_by',selectSort)" ng-model="selectSort" ng-options="sort for sort in sortings" values='<%= t('products.products.sorting_values') %>'></select>
  <%= t('.select_per') %>
  <select id="per"  ng-change="changeSelect('per',selectPer)" ng-model="selectPer" ng-options="per for per in pers" ></select>

</div>
<div class="collections" ng-controller="FavoriteController">

  <%= render @collections %>
  <div class="clear"></div>
  <%= paginate @collections %>
</div>
<div class="clear"></div>
<% content_for :seo_text do %>
  <%= render_seo_block "__collections__#{@category_group.try(:slug)}" %>
<% end %>

app/views/collections/_collections.mobile.erb
<%= render @collections %>
<div class="large-12 pagination_wrapper columns" style="text-align:center">
  <%= paginate @collections %>
</div>

app/views/collections/_filter.html.erb
<div class="filter" ng-controller="FilterController">
  <div class="block_box category_select">
    <h2><%= t('products.filter.category_title') %></h2>
    <ul>
      <% for category in create_outfit_categories(@category_group) %>
        <li class="<%= 'active' if @main_category.present? && @main_category.id == category.id %>">
          <%= link_to category.name, outfit_category_path(assigned_locale, category.slug), title: category.name %>
          <% if @main_category.present? && @main_category.id == category.id %>
          <ul>
            <% for subcategory in category.categories %>
            <li class="<%= 'active' if @category.present? && @category.id == subcategory.id %>"> 
              <%= link_to subcategory.name, outfit_category_path(assigned_locale, subcategory.slug), title: subcategory.name %></li>
            <% end %>
          </ul>
          <% end %>
        </li>  
      <% end %>
    </ul>
  </div>
</div>

app/views/collections/index.html.erb
<h1>Collections#index</h1>
<p>Find me in app/views/collections/index.html.erb</p>

app/views/collections/index.mobile.erb
<%= render @collections %>

app/views/collections/show.html.erb
<% content_for :title do %>
  <% cache ['title', @scope , @collection] do %>
<%= "#{@collection.title} | #{user_name @collection.user} | #{Settings.app.name}" %>
  <% end %>
<% end %>

<% content_for :meta do %>
    <% cache ['meta', @scope ,@collection] do %>
      <meta property="og:title" content="<%= @collection.title %> | <%= user_name @collection.user %> | <%= Settings.app.name %>"/>
      <meta property="og:type" content="website"/>
      <meta property="og:url" content="<%=collection_url(@collection.locale, @collection)%>"/>
      <meta property="og:image" content="<%=@collection.image.original.url%>"/>
      <meta property="og:image:width" content="550" />
      <meta property="og:image:height" content="650" />
      <meta property="og:locale" content="<%=assigned_locale%>" />
      <meta property="og:description" content="<%= @collection.description %>" />
      <link rel="canonical" href="<%= collection_url(@collection.locale, @collection)%>"/>

      <!--
      <PageMap>
         <DataObject type="document">
            <Attribute name="title"><%= @collection.title %></Attribute>
            <Attribute name="author"><%= user_name(@collection.user) %></Attribute>
            <Attribute name="description"><%= @collection.description %></Attribute>
            <Attribute name="category"><%= breadcrumb_collection_text @collection%></Attribute>
            <Attribute name="likes"><%= @collection.favorites_count %></Attribute>
            <Attribute name="rating">
                <%= @collection.rate_average.try(:avg) %>
            </Attribute>
            <Attribute name="last_update"><%= @collection.updated_at %></Attribute>
         </DataObject>
         <DataObject type="thumbnail">
            <Attribute name="src" value="<%= @collection.image.original.url %>" />
            <Attribute name="width" value="550" />
            <Attribute name="height" value="650" />
         </DataObject>
      </PageMap>
      -->
  <% end %>

<% end %>

<div class="collection_show" ng-controller="FavoriteController">
  <div class="leftside">
    <% cache ['content', @scope , @collection] do %>

      <h2 class="titleize"><%= @collection.title %></h2>
      <div class="image_wrapper">
        <% for item in @collection.collection_items.order(order: :asc) %>
          <a class='area' style="<%= css_calculate_dimension(item, @collection)%>"
                                  ng-click="callForm(<%= item.item_id %>)"
                                  data-information='<%= item.item_id %>infobox'>
          </a>
          <%= information_span(item.item_id, @collection) %>
        <% end %>
        <%= image_tag '', "my-src" =>@collection.image.original, title: @collection.title, alt: @collection.title %>
      </div>
      <a  class="love_button <%= favorite(@collection) %>"
          ng-click="clickFavorite('col',<%= @collection.id %>)"
          id="col<%= @collection.id %>"
          path="<%= collection_favorites_path(assigned_locale, @collection) %>"></a>

      <div class="visits">
        <%=t('action.viewed', count: @collection.visits_count) %>
      </div>
<br />

      <div class="details">
        <%= link_to t('.create_comment'), '#comment_now', id: 'call_to_action' %>
        <%= image_tag user_image(@collection.user, :smaller), alt: user_name(@collection.user), title: user_name(@collection.user)  %>
        <div class="inner">
          <h3><%= @collection.title %></h3>
          <div class="ratable">
            <%= rating_for @collection, "rate", :star => 5 %>
          </div><br />
          <%= raw t('.created_from', user: user_name(@collection.user),
                            url: user_profile(@collection.user)) %> <br />
          <%= raw t('.created_at', date: l(@collection.created_at, format: :short)) %><br /><br />
          <div class="description">
            <%= linked_description @collection %>
          </div>
        </div>
        <div class="clear"></div>
        <div class="myshare">
        <span><%= t('.share') %></span>
        <%= render_shareable  :static_link => true,
                              :title=> "#{@collection.title} | #{user_name @collection.user} | #{Settings.app.name}",
                              :button_caption => t('.share_now'),
                              :buttons=> ['twitter', 'facebook', 'tumblr', 'google_plus', 'pinterest'],
                              :media =>  @collection.image.original.url %>

        <h3><%= t('.embedd_to') %></h3>
        <textarea id="codeshare" readonly><%= render_embed_code(@collection) %></textarea>
      </div>
        <div style="clear:both"></div>
      </div>
    <% end %>

    <%= cache ['comment_box', current_user, @scope ,@collection] do %>
      <% if current_user.present? %>
      <div class="commenting_box" id="comment_now">
        <h3><%= t('.create_comment') %></h3>
        <%= form_for :comment,
                    url: collection_comments_path(locale: assigned_locale, collection_id:@collection),
                    html:{class: 'formular no_exit_popup'} do |f| %>
          <%= f.text_area :comment, placeholder: t('.your_comment') %>

          <%= f.submit t('.save_comment') ,class: 'button' %>
        <% end %>
      </div>
      <% end %>
    <% end %>

    <%= cache ['comments', current_user, @scope ,@collection.updated_at] do %>
      <%= render @collection.comments %>
    <% end %>

  </div>
  <div class="productviews">

    <h2><%= t('.used_products') %></h2>
      <%= cache ['product_list', @scope ,@collection] do %>
        <% for product in @collection.products %>
          <%= render 'products/small_product', product: product %>
        <% end %>
      <% end %>
  </div>
  <div style="clear:both"></div>
</div>

<%= render 'shared/exit_popup', path_to_intent: outfit_category_path(@collection.scope.locale, @collection.category.slug), products: @collection.products.try(:first).try(:similar_products).try(:limit, 3) %>

app/views/collections/show.mobile.erb
<% content_for :title do %>
  <% cache ['title', @scope , @collection] do %>
<%= "#{@collection.title} | #{user_name @collection.user} | #{Settings.app.name}" %>
  <% end %>
<% end %>

<% content_for :meta do %>
    <% cache ['meta', @scope ,@collection] do %>
      <meta property="og:title" content="<%= @collection.title %> | <%= user_name @collection.user %> | <%= Settings.app.name %>"/>
      <meta property="og:type" content="website"/>
      <meta property="og:url" content="<%=collection_url(@collection.locale, @collection)%>"/>
      <meta property="og:image" content="<%=@collection.image.original.url%>"/>
      <meta property="og:image:width" content="550" />
      <meta property="og:image:height" content="650" />
      <meta property="og:locale" content="<%=assigned_locale%>" />
      <meta property="og:description" content="<%= @collection.description %>" />
      <link rel="canonical" href="<%= collection_url(@collection.locale, @collection)%>"/>

      <!--
      <PageMap>
         <DataObject type="document">
            <Attribute name="title"><%= @collection.title %></Attribute>
            <Attribute name="author"><%= user_name(@collection.user) %></Attribute>
            <Attribute name="description"><%= @collection.description %></Attribute>
            <Attribute name="category"><%= breadcrumb_collection_text @collection%></Attribute>
            <Attribute name="likes"><%= @collection.favorites_count %></Attribute>
            <Attribute name="rating">
                <%= @collection.rate_average.try(:avg) %>
            </Attribute>
            <Attribute name="last_update"><%= @collection.updated_at %></Attribute>
         </DataObject>
         <DataObject type="thumbnail">
            <Attribute name="src" value="<%= @collection.image.original.url %>" />
            <Attribute name="width" value="550" />
            <Attribute name="height" value="650" />
         </DataObject>
      </PageMap>
      -->
  <% end %>

<% end %>
<div class="detail_wrapper">
  <%= render @collection %>
  <div class="small-10 small-push-1">
    <%= @collection.description %>
    <br />
    <%=t('action.viewed', count: @collection.visits_count) %>
    <h2><%= t('.used_products') %></h2>
  </div>
  <div class"row" ng-controller="FavoriteController">

    <% for product in @collection.products %>
      <div class="small-5 small-push-1 columns product_preview">
        <%= render 'products/small_product', product: product, formats: [:mobile]%>
      </div>
    <% end %>
    <div class="small-5 small-push-1 columns">
    </div>
  </div>
</div>