config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Fashionfly::Application.routes.draw do
  get 'app-entwickler-finden', to: 'redirector#appentwickler', as: 'app'
  get 'programmierer-hamburg', to: 'redirector#programmierer', as: 'prog'
  get 'internet-agentur-hamburg', to: 'redirector#internetagentur', as: 'int'

  get 'brandet_categories/show'

  get 'blogs/edit'

  get 'blogs/show'

  admin_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:is_admin?) && current_user.is_admin?
  end

  team_constraint  = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:is_team?) && current_user.is_team?
  end

  post '/rate' => 'rater#create', :as => 'rate'
  constraints team_constraint do
    mount Lit::Engine => '/lit'
  end

  namespace :backend do
    constraints admin_constraint do
      mount Sidekiq::Web => '/sidekiq'
    end
    root to: 'dashboards#show'
    resources :configurations
    resources :scopes do
      resources :outfit_categories
      resources :categories
      resources :contests
      resources :pages
      resources :affiliates do
        resources :mappings
      end
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    confirmations: 'users/confirmations',
                                    registrations: 'users/registrations' }

  resources :widgets

  namespace :endpoint do
    namespace :v1 do
      scope defaults: { format: 'json' } do
        resources :scopes, only: %i[index show] do
          resources :categories, only: %i[index show]
          resources :products, only: %i[index show]
          resources :collections_categories, only: %i[index show]
          resources :collections, except: :destroy do
            resources :comments
          end
          resources :users
          resources :session
        end
      end
    end
  end

  scope '/:locale' do
    get 'hashtags/:hashtag',   to: 'hashtags#show',      as: :hashtag
    get 'hashtags',            to: 'hashtags#index',     as: :hashtags
    resources :shops
    resources :banners
    resources :entries
    resources :brands, only: %i[show index]
    get 'property_shop_link', to: 'properties#property_shop_link', as: :property_shop_link
    get 'property_collection_link', to: 'properties#property_collection_link', as: :property_collection_link
    get 'property_category_link', to: 'properties#property_category_link', as: :property_category_link

    resource :property, only: %i[edit update]
    get 'shoplist', to: 'shops#list', as: :shoplist
    get 'shopref/:id', to: 'shops#ref', as: :shopref
    get 'language', to: 'welcome#language'
    resources :contests
    resources :styles, only: %i[show index]
    resources :profiles, only: %i[show update edit] do
      get 'outfits', to: 'profiles#outfits'
      get 'favorites', to: 'profiles#favorites'
      resource :blog
    end
    get '/product_clicked/:id', to: 'products#clicked', as: :prodclick
    patch 'email_edit', to: 'profiles#email_edit', as: :email_edit
    get 'prodref/:id', to: 'products#ref', as: :productref
    resources :products, only: %i[show index] do
      resources :favorites, only: %i[create destroy]
    end
    resources :collections, only: %i[show index] do
      resources :favorites, only: %i[create destroy]
      resources :comments, only: %i[create destroy update]
    end
    post 'product_partner', to: 'products#refshop', as: :refshop
    resources :categories
    resources :outfit_categories
    mount FashionFlyEditor::Engine => '/combine'
    namespace :api do
      match 'categories', to: 'categories#index', via: [:options]
      resources :categories
      resources :colors
      resources :products
    end
    get 'login', to: 'users#new', as: 'login'
    get 'faq', to: 'static#faq', as: 'faq'
    get 'about', to: 'static#about', as: 'about'
    get 'team', to: 'static#team', as: 'team'
    get 'disclaimer', to: 'static#disclaimer', as: 'disclaimer'
    get 'terms', to: 'static#terms', as: 'terms'
    get 'impress', to: 'static#impress', as: 'impress'
    get 'privacy', to: 'static#privacy', as: 'privacy'
    get 'sitemap.xml', to: 'welcome#sitemap', format: :xml, as: 'sitemap', defaults: { format: 'xml' }
    get 'robots.txt', to: 'welcome#robot', format: :text, as: 'robot', defaults: { format: 'text' }
    root 'welcome#index'
    get ':brand/:category', to: 'brandet_categories#show', as: 'brand_category'
  end

  # Parameter constraint checks if path does not begin with locale and only in that case redirects to localized version. This way we will avoid infinite redirects for non-existing urls.
  get '/*path', to: 'language#select', constraints: { path: %r{(?!(#{I18n.available_locales.join("|")})/).*} },
                format: false
end

app/models/shop.rb
# frozen_string_literal: true

class Shop < ActiveRecord::Base
  belongs_to :scope
  has_many :banners

  validates :name, presence: true
  validates :logo, presence: true
  validates :body, presence: true
  validates :link, presence: true

  mount_uploader :logo, ShoplogoUploader
end

app/controllers/shops_controller.rb
# frozen_string_literal: true

class ShopsController < ScopeController
  before_action :find_shop, only: %i[show edit update destroy ref]
  load_and_authorize_resource param_method: :shop_attributes, except: :ref

  def index
    @shops = @scope.shops
  end

  def list
    @shops = @scope.shops
  end

  def ref
    redirect_to @shop.link
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_attributes)
    @shop.scope_id = @scope.id
    if @shop.save
      flash[:notice] = t('action.created', entity: Shop.model_name.human)
      redirect_to shoplist_path(assigned_locale)
    else
      flash.now[:alert] = t('action.error')
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @shop.update(shop_attributes)
      flash[:notice] = t('action.updated', entity: Shop.model_name.human)
      redirect_to shoplist_path(assigned_locale)
    else
      flash.now[:alert] = t('action.error')
      render 'edit'
    end
  end

  def destroy
    @shop.destroy if @shop.present?
    flash[:notice] = t('action.destroyed', entity: Shop.model_name.human)
    redirect_to shoplist_path(assigned_locale)
  end

  protected

  def find_shop
    @shop = Shop.find(params[:id])
  end

  def shop_attributes
    params.require(:shop).permit(:name,
                                 :logo,
                                 :favorite,
                                 :logo_cache,
                                 :body,
                                 :link,
                                 :position,
                                 :sidebar_banner,
                                 :top_banner,
                                 :bottom_banner)
  end
end

app/helpers/shops_helper.rb
# frozen_string_literal: true

module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_for shop, url: (shop.new_record? ?
                      shops_path(assigned_locale) :
                      shop_path(assigned_locale, shop)
                   ), 
                   html:{class: 'formular profile_edit'} do |f| %>

  <div>
      <%= f.label :name, class: 'label' %>
      <%= f.text_field :name %>
  </div>

  <div>
      <%= f.label :link, class: 'label' %>
      <%= f.text_field :link %>
  </div>

  <div>
      <%= f.check_box :favorite %>
      <%= f.label :favorite %>
  </div>

  <div>
      <%= f.label :logo, class: 'label' %>
      <div class="upload_box">
        <%= image_tag f.object.logo %><br />
        <%= f.hidden_field :logo_cache %>
        <%= f.file_field :logo %>
      </div>
  </div>
  
  <div>
    <%= f.label :body, class: 'label' %>
    <%= f.text_area :body, class: 'tinymce' %>
  </div>

  <div>
    <%= f.label :sidebar_banner, class: 'label' %>
    <%= f.text_area :sidebar_banner %>
  </div>

  <div>
    <%= f.label :top_banner, class: 'label' %>
    <%= f.text_area :top_banner %>
  </div>  

  <div>
    <%= f.label :bottom_banner, class: 'label' %>
    <%= f.text_area :bottom_banner %>
  </div>

  <div>
      <%= f.label :position, class: 'label' %>
      <%= f.text_field :position %>
  </div>

  <div class="action">
    <%= f.submit t('.save_shop'), class: 'button' %>
  </div>


  <div class="clear"></div>
<% end %>

app/views/shops/_navigation.html.erb
<div class="navigation">
  <div class="block_box navigation_select">
  <h2><%= t('profiles.navigation.title') %></h2>
  <ul>
    <li><%= link_to t('shared.header.shoplist'), shoplist_path(assigned_locale) %></li>
    <li><%= link_to t('shared.header.banners'), banners_path(assigned_locale) %></li>
    <li><%= link_to t('shared.header.properties'), 
                    edit_property_path(locale:assigned_locale)%>
    </li>
  </ul>
</div>
</div>

app/views/shops/_shop.html.erb
<div class="shopwrapper">
  <div class="logo_container">
    <%= link_to image_tag(shop.logo, alt: shop.name), 
                shopref_path(assigned_locale, shop),
                title: shop.name,
                :rel => 'nofollow' %>
  </div>

  <%= link_to t('.details'),
              shop_path(assigned_locale, shop),
              title: shop.name,
              class: 'detail_link' %>

</div>

app/views/shops/edit.html.erb
<div class="container">
  <%= render 'navigation',  active: {profile: 'active' } %>
  <div class="profile_formular">
    <h1> <%= t 'action.edit_shop' %></h1>
    <%= render 'form', shop: @shop %>
  </div>
  <div class="clear"></div>
</div>

app/views/shops/index.html.erb
<div class="shops_banners">
<%= render @shops %>
</div>

app/views/shops/list.html.erb
<div class="container">
  <%= render 'navigation',  active: {profile: 'active' } %>
  <div class="profile_formular">
    <h1> <%= t '.title' %></h1>
    <%= link_to t('action.new'), new_shop_path, class: 'button' %>
    <br />    <br />
    <br />

    <% if @shops.present? %>
    <table class="listing">
      <tr>
        <th><%= t('.logo') %></th>
        <th><%= t('.name') %></th>
        <th class="list_action"><%= t('.actions') %></th>
      </tr>
      <% for shop in @shops %>
        <tr class="inside">
          <td class="small"><%= image_tag shop.logo %></td>
          <td><%= shop.name %></td>
          <td class="list_action">
            <%= link_to t('action.show'),     shop_path(assigned_locale, shop) %> |
            <%= link_to t('action.edit'),     edit_shop_path(assigned_locale, shop) %> |
            <%= link_to t('action.destroy'),  shop_path(assigned_locale, shop), 
                                              :method => :delete,
                                              :confirm => t('action.destroy_confirm', entity: Shop.model_name) %>
          </td>
        <tr>
      <% end %>
    </table>
    <% end %>
  </div>
  <div class="clear"></div>
</div>

app/views/shops/new.html.erb
<div class="container">
  <%= render 'navigation',  active: {profile: 'active' } %>
  <div class="profile_formular">
    <h1> <%= t 'action.new_shop' %></h1>
    <%= render 'form', shop: @shop %>
  </div>
  <div class="clear"></div>
</div>

app/views/shops/show.html.erb
<div class="container">
  <div class="white_box shop">
    <div class="sidebar">
      <%=link_to  image_tag(@shop.logo, alt: @shop.name), 
                  shopref_path(id:@shop.id), 
                  title: @shop.name,
                  :rel => 'nofollow'%>
      <br />
      <% if @shop.sidebar_banner.present? %>
      <br />
        <%= raw @shop.sidebar_banner %>
      <% end %>
    </div>
    <div class="block">
      <% if can? :edit, Shop %>
      <%= link_to t('action.edit'),  edit_shop_path(assigned_locale, @shop),
                                  class: 'button'%>
      <br /><br />
      <% end %>
      <% if @shop.top_banner.present?  %>
        <%= raw @shop.top_banner %>
        <br />
        <br />
      <% end %>
      <%= simple_format @shop.body %>
      <% if @shop.bottom_banner.present? %>
        <br />
        <%= raw @shop.bottom_banner %>
      <% end %>
    </div>
    <div class="clear"></div>
  </div>
</div>