config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Fashionfly::Application.routes.draw do
  get 'app-entwickler-finden', to: 'redirector#appentwickler', as: 'app'
  get 'programmierer-hamburg', to: 'redirector#programmierer', as: 'prog'
  get 'internet-agentur-hamburg', to: 'redirector#internetagentur', as: 'int'

  get 'brandet_categories/show'

  get 'blogs/edit'

  get 'blogs/show'

  admin_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:is_admin?) && current_user.is_admin?
  end

  team_constraint  = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:is_team?) && current_user.is_team?
  end

  post '/rate' => 'rater#create', :as => 'rate'
  constraints team_constraint do
    mount Lit::Engine => '/lit'
  end

  namespace :backend do
    constraints admin_constraint do
      mount Sidekiq::Web => '/sidekiq'
    end
    root to: 'dashboards#show'
    resources :configurations
    resources :scopes do
      resources :outfit_categories
      resources :categories
      resources :contests
      resources :pages
      resources :affiliates do
        resources :mappings
      end
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    confirmations: 'users/confirmations',
                                    registrations: 'users/registrations' }

  resources :widgets

  namespace :endpoint do
    namespace :v1 do
      scope defaults: { format: 'json' } do
        resources :scopes, only: %i[index show] do
          resources :categories, only: %i[index show]
          resources :products, only: %i[index show]
          resources :collections_categories, only: %i[index show]
          resources :collections, except: :destroy do
            resources :comments
          end
          resources :users
          resources :session
        end
      end
    end
  end

  scope '/:locale' do
    get 'hashtags/:hashtag',   to: 'hashtags#show',      as: :hashtag
    get 'hashtags',            to: 'hashtags#index',     as: :hashtags
    resources :shops
    resources :banners
    resources :entries
    resources :brands, only: %i[show index]
    get 'property_shop_link', to: 'properties#property_shop_link', as: :property_shop_link
    get 'property_collection_link', to: 'properties#property_collection_link', as: :property_collection_link
    get 'property_category_link', to: 'properties#property_category_link', as: :property_category_link

    resource :property, only: %i[edit update]
    get 'shoplist', to: 'shops#list', as: :shoplist
    get 'shopref/:id', to: 'shops#ref', as: :shopref
    get 'language', to: 'welcome#language'
    resources :contests
    resources :styles, only: %i[show index]
    resources :profiles, only: %i[show update edit] do
      get 'outfits', to: 'profiles#outfits'
      get 'favorites', to: 'profiles#favorites'
      resource :blog
    end
    get '/product_clicked/:id', to: 'products#clicked', as: :prodclick
    patch 'email_edit', to: 'profiles#email_edit', as: :email_edit
    get 'prodref/:id', to: 'products#ref', as: :productref
    resources :products, only: %i[show index] do
      resources :favorites, only: %i[create destroy]
    end
    resources :collections, only: %i[show index] do
      resources :favorites, only: %i[create destroy]
      resources :comments, only: %i[create destroy update]
    end
    post 'product_partner', to: 'products#refshop', as: :refshop
    resources :categories
    resources :outfit_categories
    mount FashionFlyEditor::Engine => '/combine'
    namespace :api do
      match 'categories', to: 'categories#index', via: [:options]
      resources :categories
      resources :colors
      resources :products
    end
    get 'login', to: 'users#new', as: 'login'
    get 'faq', to: 'static#faq', as: 'faq'
    get 'about', to: 'static#about', as: 'about'
    get 'team', to: 'static#team', as: 'team'
    get 'disclaimer', to: 'static#disclaimer', as: 'disclaimer'
    get 'terms', to: 'static#terms', as: 'terms'
    get 'impress', to: 'static#impress', as: 'impress'
    get 'privacy', to: 'static#privacy', as: 'privacy'
    get 'sitemap.xml', to: 'welcome#sitemap', format: :xml, as: 'sitemap', defaults: { format: 'xml' }
    get 'robots.txt', to: 'welcome#robot', format: :text, as: 'robot', defaults: { format: 'text' }
    root 'welcome#index'
    get ':brand/:category', to: 'brandet_categories#show', as: 'brand_category'
  end

  # Parameter constraint checks if path does not begin with locale and only in that case redirects to localized version. This way we will avoid infinite redirects for non-existing urls.
  get '/*path', to: 'language#select', constraints: { path: %r{(?!(#{I18n.available_locales.join("|")})/).*} },
                format: false
end

app/models/category.rb
# frozen_string_literal: true

class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :products, through: :categorizations
  has_many :categories, dependent: :destroy
  belongs_to :category
  belongs_to :scope
  has_and_belongs_to_many :icons
  has_and_belongs_to_many :brands, uniq: true

  validates :name, presence: true
  validates :scope_id, presence: true
  validates :slug, uniqueness: true

  before_save :update_slug
  before_save :update_position
  after_save :update_leaf

  def update_slug
    default = create_slug(self)
    myslug = default
    counter = 0
    other_category = Category.where(slug: myslug).first
    while other_category.present? && other_category.id != id
      counter += 1
      myslug = "#{default}_#{counter}"
      other_category = Category.where(slug: myslug).first
    end
    self.slug = myslug
  end

  def create_slug(category)
    return '' if category.blank?

    parent = category.category
    parent_slug = "#{create_slug(parent)}_"
    parent_slug + clean_name(category.name).try(:downcase)
  end

  def update_position
    return if position.present?

    self.position = Category.count + 1
  end

  def update_leaf
    category.update_leaf if category.present? && category.leaf
    return if leaf && categories.count.zero? || (leaf.blank? || !leaf) && categories.count.positive?

    self.leaf = categories.count.zero?
    save
  end

  def name_with_parent
    slug.gsub('_', ' ')
  end

  def brands
    products.joins(:brand).group(:name)
  end

  private

  def clean_name(name)
    return '' if name.blank?

    name.gsub('ö', 'oe').gsub('ü', 'ue').gsub('ä', 'ae').gsub('ß', 'ss').gsub('%', '').gsub(' ', '_').gsub('&', 'und')
  end
end

app/controllers/api/categories_controller.rb
# frozen_string_literal: true

module Api
  class CategoriesController < Api::ApiController
    def index
      @options = create_options
      @categories = @scope.categories.where(main_taxon: true)
    end

    def show
      @category = @scope.categories.where(id: params[:id]).first
    end

    protected

    def create_options
      result = []

      scope_option = {}
      scope_option[:name] = 'scope'
      scope_option[:type] = 'hidden'
      scope_option[:value] = @scope.id
      scope_option[:label] = ''
      result << scope_option
      if @scope.has_contest?
        contest_option = {}
        contest_option[:name] = 'contest'
        contest_option[:type] = 'checkbox'
        contest_option[:value] = 1
        contest_option[:label] = I18n.t('activerecord.attributes.contest.form_label')
        result << contest_option
      end
      if current_user.present?
        user_option = {}
        user_option[:name] = 'user'
        user_option[:type] = 'hidden'
        user_option[:value] = current_user.secret
        user_option[:label] = ''
        result << user_option
      end

      result
    end
  end
end

app/controllers/backend/affiliates_controller.rb
# frozen_string_literal: true

module Backend
  class AffiliatesController < Backend::BackendController
    before_action :find_scope

    def index
      @affiliates = Affiliate.where(scope_id: @scope.id)
    end

    def new
      @affiliate = Affiliate.new
    end

    def create
      @affiliate = @scope.affiliates.build(affiliate_attributes)
      if @affiliate.save
        flash[:notice] = 'Speichern Erfolgreich'
        redirect_to backend_scope_affiliate_path(@scope, @affiliate)
      else
        flash[:error] = 'Fehler beim Speiechern'
        render 'new'
      end
    end

    def show
      @affiliate = @scope.affiliates.where(id: params[:id]).first
      @unmapped_categories = @affiliate.categories

      @affiliate.mappings.each do |mapping|
        @unmapped_categories.delete(mapping.name)
      end

      @unmapped_categories.each do |unmapped_category|
        @affiliate.mappings.build(name: unmapped_category)
      end
    end

    def edit
      @affiliate = @scope.affiliates.where(id: params[:id]).first
    end

    def update
      @affiliate = @scope.affiliates.where(id: params[:id]).first
      @affiliate.update(affiliate_attributes)
      @unmapped_categories = @affiliate.categories

      @affiliate.mappings.each do |mapping|
        @unmapped_categories.delete(mapping.name)
      end

      @unmapped_categories.each do |unmapped_category|
        @affiliate.mappings.build(name: unmapped_category)
      end

      render 'show'
    end

    protected

    def find_scope
      @scope = Scope.find(params[:scope_id])
    end

    def affiliate_attributes
      params.require(:affiliate).permit(:name,
                                        :logo,
                                        :file,
                                        :importer,
                                        :item_tag,
                                        :category_tag,
                                        :category_split_char,
                                        :ean_tag,
                                        :image_tag,
                                        :name_tag,
                                        :number_tag,
                                        :description_tag,
                                        :brand_tag,
                                        :price_tag,
                                        :currency_code_tag,
                                        :shipping_cost_tag,
                                        :delivery_time_tag,
                                        :last_modified_tag,
                                        :link_tag,
                                        :ready,
                                        :pay_invoice,
                                        :free_shipping,
                                        :premium,
                                        :replace_only_images,
                                        mappings_attributes: %i[id name category_id])
    end
  end
end

app/controllers/backend/backend_controller.rb
# frozen_string_literal: true

module Backend
  class BackendController < ApplicationController
    layout 'backend'

    before_action :authenticate_user!
    before_action :has_access

    def get_right_scope; end

    def assigned_locale
      'de'
    end

    private

    def has_access
      return if current_user.is_admin?

      redirect_to root_path(assigned_locale)
    end
  end
end

app/controllers/backend/categories_controller.rb
# frozen_string_literal: true

module Backend
  class CategoriesController < Backend::BackendController
    before_action :find_scope
    respond_to :json

    def index
      @categories = @scope.categories
    end

    def create
      @category = Category.new(category_attributes)
      if @category.save
        flash[:notice] = 'Erfolgreich gespeichert'
      else
        flash[:error] = 'Nicht gespeichert'
      end
      redirect_to backend_scope_categories_path(@scope)
    end

    def update
      @category = Category.find(params[:id])
      if @category.update(category_attributes)
        flash[:notice] = 'Erfolgreich aktualisiert'
      else
        flash[:error] = 'Änderungen nicht gespeichert'
      end
      redirect_to backend_scope_categories_path(@scope)
    end

    def destroy
      @scope.categories.where(id: params[:id]).first.try(:destroy)
      redirect_to backend_scope_categories_path(@scope)
    end

    protected

    def find_scope
      @scope = Scope.find(params[:scope_id])
    end

    def category_attributes
      params.require('category').permit(:name,
                                        :main_taxon,
                                        :scope_id,
                                        :category_id,
                                        :position,
                                        :icon_ids)
    end
  end
end

app/controllers/backend/configurations_controller.rb
# frozen_string_literal: true

module Backend
  class ConfigurationsController < Backend::BackendController
    before_action :find_configuration, only: %i[show edit update destroy]

    def index
      @configurations = ::Configuration.all
    end

    def show; end

    def new
      @configuration = ::Configuration.new
    end

    def create
      @configuration = ::Configuration.new(configuration_attributes)
      if @configuration.save
        flash[:notice] = 'Speichern Erfolgreich'
        redirect_to backend_configuration_path(@configuration)
      else
        flash.now[:error] = 'Konnte nicht Speichern'
        render 'new'
      end
    end

    def edit; end

    def update
      if @configuration.update(configuration_attributes)
        flash[:notice] = 'Änderungen Erfolgreich'
        redirect_to backend_configuration_path(@configuration)
      else
        flash.now[:error] = 'Konnte nicht Speichern'
        render 'edit'
      end
    end

    def destroy
      @configuration.destroy
      redirect_to backend_configurations_path
    end

    protected

    def find_configuration
      @configuration = ::Configuration.find(params[:id])
    end

    def configuration_attributes
      params.require(:configuration).permit(:key, :value)
    end
  end
end

app/controllers/backend/contests_controller.rb
# frozen_string_literal: true

module Backend
  class ContestsController < Backend::BackendController
    before_action :find_scope

    def index
      @contests = @scope.contests.page(params[:page]).per(5)
    end

    def new
      @contest = @scope.contests.new
    end

    def create
      @contest = @scope.contests.new(contest_attributes)
      @contest.scope_id = @scope.id
      if @contest.save!
        redirect_to backend_scope_contest_path(@scope, @contest)
      else
        render 'new'
      end
    end

    def show
      @contest = Contest.find(params[:id])
    end

    def edit
      @contest = Contest.find(params[:id])
    end

    def update
      @contest = Contest.find(params[:id])
      if @contest.update(contest_attributes)
        redirect_to backend_scope_contest_path(@scope, @contest)
      else
        render 'edit'
      end
    end

    def destroy
      @contest = Contest.find(params[:id])
      @contest.destroy if @contest.present?
      redirect_to backend_scope_contests_path(@scope)
    end

    private

    def find_scope
      @scope = Scope.find(params[:scope_id])
    end

    def contest_attributes
      params.require(:contest).permit(:title, :body, :banner, :finished)
    end
  end
end

app/controllers/backend/dashboards_controller.rb
# frozen_string_literal: true

module Backend
  class DashboardsController < Backend::BackendController
  end
end

app/controllers/backend/mappings_controller.rb
# frozen_string_literal: true

module Backend
  class MappingsController < Backend::BackendController
  end
end

app/helpers/backend/affiliates_helper.rb
# frozen_string_literal: true

module Backend
  module AffiliatesHelper
    def affiliate_key(affiliate)
      affiliate.updated_at.to_s
    end

    def affiliate_mapping(affiliate, mapping)
      "#{affiliate_key(affiliate)}-#{mapping.name}"
    end
  end
end

app/helpers/backend/backend_helper.rb
# frozen_string_literal: true

module Backend
  module BackendHelper
    def activate(items)
      items.each do |item|
        return 'active' if controller.controller_path == "backend/#{item}"
      end
      ''
    end
  end
end

app/helpers/backend/categories_helper.rb
# frozen_string_literal: true

module Backend
  module CategoriesHelper
    def filter_main_categories(categories)
      @main_taxon ||= categories.map { |c| c if c.main_taxon }.compact
    end

    def filter_child_categories(categories, category)
      categoy_cache[category.id] ||= categories.map { |c| c if c.category_id == category.id }.compact
    end

    def is_parent_main_group?(categories, category)
      return parent_cache[category.id] if parent_cache[category.id].present?

      parent = categories.map { |c| c if c.id == category.category_id }.compact.first
      parent_cache[category.id] = parent.present? && parent.main_taxon
    end

    def icon_categories
      @icons ||= Icon.all
    end

    def categoy_cache
      @categoy_cache ||= {}
    end

    def parent_cache
      @parent_cache ||= {}
    end
  end
end

app/helpers/backend/contests_helper.rb
# frozen_string_literal: true

module Backend
  module ContestsHelper
  end
end

app/helpers/backend/dashboards_helper.rb
# frozen_string_literal: true

module Backend
  module DashboardsHelper
  end
end

app/helpers/backend/mappings_helper.rb
# frozen_string_literal: true

module Backend
  module MappingsHelper
  end
end

app/views/backend/categories/_category.html.erb
<li class="category">
  <div class="pre_action">
    <% if filter_child_categories(@categories, category) %>
      <%= link_to image_tag('arrow_down.png'), '#', class: 'arrow_down' %>
      <%= link_to image_tag('arrow_right.png'), '#', class: 'arrow_right' %>
    <% end %>
    <%= link_to image_tag('plus.png'), '#', class: 'add_button' %>
  </div>
  <span class="name">
    <%= category.name %>
  </span>
  <div class="action">
    <%= link_to image_tag('edit.png'), '#', class: 'edit_button'%>


    <%= link_to image_tag('delete.png'), backend_scope_category_path(@scope, category), class: 'delete_button', :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"  %>
  </div>
  <div class="clear"></div>
  <div class="formular">
      <%= form_for :category, 
                  url: backend_scope_categories_path(@scope), 
                  html: { :class => :form, id: 'main_category_form' } do |f| %>
        <%= f.label :name, class: 'label'  %>
        <%= f.text_field :name, class: 'text_field' %>
        <% if category.main_taxon %>
          <%= f.label :icons, class: 'label'  %>
          <%= collection_select :category, :icon_ids, icon_categories, :id, :name, {:name => 'category[icon_ids][]'}%>
        <% end %>
        <%= f.hidden_field :main_taxon, value: false %>
        <%= f.hidden_field :scope_id, value: @scope.id %>
        <%= f.hidden_field :category_id, value: category.id %>
        <div class="action">
          <br />
          <%= f.submit 'Anlegen', class: 'button' %>
        </div>
      <% end %>
  </div>
  <div class="clear"></div>


  <div class="edit_formular">
      <%= form_for category, 
                  url: backend_scope_category_path(@scope, category), 
                  html: { :class => :form, id: 'main_category_form' } do |f| %>
        <%= f.label :name, class: 'label'  %>
        <%= f.text_field :name, class: 'text_field' %>
        <% if is_parent_main_group?(@categories, category) %>
          <%= f.label :icons, class: 'label'  %>
          <%= collection_select :category, :icon_ids, icon_categories, :id, :name, {:name => 'category[icon_ids][]'}%>
        <% end %>
        <div class="action">
          <br />
          <%= f.submit 'Änderung speichern', class: 'button' %>
        </div>
      <% end %>
  </div>
  <div class="clear"></div>

  <% if filter_child_categories(@categories, category) %>
    <ul class="subcat">
      <%= render filter_child_categories(@categories, category) %>
    </ul>
  <% end %>
</li>

app/views/backend/categories/_form.html.erb
  <div class="group">
    <%= f.label :name, t("activerecord.attributes.category.name", :default => "Name"), :class => :label %>
    <%= f.text_field :name, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :category_id, t("activerecord.attributes.category.category_id", :default => "Category"), :class => :label %>
    <%= f.number_field :category_id, :class => 'number_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :slug, t("activerecord.attributes.category.slug", :default => "Slug"), :class => :label %>
    <%= f.text_field :slug, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :scope_id, t("activerecord.attributes.category.scope_id", :default => "Scope"), :class => :label %>
    <%= f.number_field :scope_id, :class => 'number_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :main_taxon, t("activerecord.attributes.category.main_taxon", :default => "Main taxon"), :class => :label %>
    <%= f.check_box :main_taxon, :class => 'check_box' %>
    <span class="description">Ex: a simple text</span>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), backend_categories_path, :class => "text_button_padding link_button" %>
</div>

app/views/backend/categories/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", backend_categories_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_backend_category_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_backend_category_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Category</h2>
    <div class="inner">
      <%= form_for @category, :url => backend_category_path(@category), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/backend/categories/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", backend_scope_categories_path(@scope)  %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Kategorie in <%= @scope.country_code %> </h2>
    <div class="inner">
     <div class="form">
      <%= form_for :category, 
                  url: backend_scope_categories_path(@scope), 
                  html: { :class => :form, id: 'main_category_form' } do |f| %>
        <%= f.label :name, class: 'label'  %>
        <%= f.text_field :name, class: 'text_field' %>
        <%= f.hidden_field :main_taxon, value: true %>
        <%= f.hidden_field :scope_id, value: @scope.id %>
        <br />
        <div class="action">
                  <br />

          <%= f.submit 'Hauptkategorie anlegen', class: 'button' %>
        </div>
      <% end %>
      <div class="clear"></div>
      </div>
    <ul class="tree">

      <%= render filter_main_categories @categories %>
    </ul>
    </div>
  </div>
</div>

app/views/backend/categories/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", backend_categories_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_backend_category_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Category</h2>
    <div class="inner">
      <%= form_for :category, :url => backend_categories_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/backend/categories/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", backend_categories_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_backend_category_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", backend_category_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.backend_category.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</b>
          <%= @category.name %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.backend_category.category_id", :default => t("activerecord.labels.category_id", :default => "Category")) %>:</b>
          <%= @category.category_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.backend_category.slug", :default => t("activerecord.labels.slug", :default => "Slug")) %>:</b>
          <%= @category.slug %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.backend_category.scope_id", :default => t("activerecord.labels.scope_id", :default => "Scope")) %>:</b>
          <%= @category.scope_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.backend_category.main_taxon", :default => t("activerecord.labels.main_taxon", :default => "Main taxon")) %>:</b>
          <%= @category.main_taxon %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_backend_category_path(@category), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), backend_category_path(@category), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>